In [1]:
#Links úteis para entender como funcionam as arrays
#https://stackoverflow.com/questions/54836757/why-are-3d-numpy-arrays-printed-the-way-they-are-how-are-they-ordered
#https://stackoverflow.com/questions/19389910/in-python-numpy-what-is-a-dimension-and-axis
#http://jalammar.github.io/visual-numpy/   

In [2]:
#importando o numpy
import numpy as np

In [3]:
#Básico

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#Criando uma array de duas dimensões
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [5]:
#Obtendo a dimensão da array
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#Obtendo o shape da array
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [7]:
#Conferindo  a quantidade de elementos, o tipo de byte, a o tamanho de cada elemento e a memória ocupada em bytes

print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)



print(a.size)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

5
int32
4
20
5
float64
8
48


### Acessando e alterando elementos, linhas, colunas, etc

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [9]:
#Obtendo um elemento específico [linha,coluna]
#obtendo o número treze
#Lembrando que no python começa a contar os elementos do zero e não do um
print(a[1,5]) # Linha 1 e coluna 5
print(a[1,-2]) #Contando as linhas de trás para frente, nesse caso começa do 1 e não do 0

13
13


In [10]:
#Obtendo uma linha especifica, os dois pontos significam que são todas as colunas
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#Obtendo uma coluna especifica, os dois pontos significam que são todas as colunas
a[:,2]

array([ 3, 10])

In [12]:
#Obtendo os dados sendo um pouco mais específico[inicio:fim:intervalo]
a[0,1:6:2]

array([2, 4, 6])

In [13]:
#Substituindo valores por posição
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [14]:
#Substituindo valores em um intervalo
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [15]:
#Substituindo valores em um intervalo usando dois valores
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [16]:
#Criando uma array de 3dimensões

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
arr = np.arange(24).reshape(2,3,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
arr.shape

(2, 3, 4)

In [19]:
arr[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
a = np.zeros(shape=[4, 4, 4])

In [22]:
a.ndim

3

In [23]:
arr2 = np.arange(72).reshape(2,6,6)
print(arr2)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]
  [60 61 62 63 64 65]
  [66 67 68 69 70 71]]]


In [24]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [26]:
#Criando diferentes tipos de arrays

In [27]:
#criar uma array preenchida de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
#é possível definir o shape [linha,coluna]
np.zeros(shape = [4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
#é possível definir o shape [dimensões,linha,coluna]
np.zeros(shape = [2,3,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
#Também é possível criar usando o 1, é possível definir o tipo de byte
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [31]:
#Qualquer outro número
np.full((2,2,3), 99, dtype = 'float32')

array([[[99., 99., 99.],
        [99., 99., 99.]],

       [[99., 99., 99.],
        [99., 99., 99.]]], dtype=float32)

In [32]:
#Criando uma array baseada em outra
np.full_like(a, 4)

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [33]:
#números aleatórios decimais
np.random.rand(4,4,4)

array([[[0.92850505, 0.29075168, 0.14216803, 0.80672033],
        [0.18861467, 0.18687717, 0.61221426, 0.20152104],
        [0.09229469, 0.57309063, 0.79405368, 0.17556249],
        [0.84427501, 0.74127997, 0.90901728, 0.50297285]],

       [[0.62385548, 0.48977259, 0.09994   , 0.44253126],
        [0.5062427 , 0.67637586, 0.72737875, 0.56864747],
        [0.77394742, 0.86797802, 0.06088607, 0.34926533],
        [0.64065071, 0.68997502, 0.82789173, 0.00710972]],

       [[0.01584443, 0.02368759, 0.65138525, 0.11439118],
        [0.21964205, 0.04596392, 0.78843054, 0.8724594 ],
        [0.94866259, 0.90267506, 0.66044063, 0.89449131],
        [0.49837011, 0.92110663, 0.38982505, 0.95053378]],

       [[0.38959164, 0.76998491, 0.493813  , 0.32786066],
        [0.72377698, 0.64225385, 0.0739524 , 0.51541637],
        [0.18296352, 0.40905656, 0.33504378, 0.16141423],
        [0.55792605, 0.74663081, 0.75491435, 0.80224394]]])

In [34]:
#números aleatórios inteiros
np.random.randint(10, size = (3,3,3))

array([[[5, 2, 7],
        [9, 3, 7],
        [1, 6, 6]],

       [[1, 1, 2],
        [7, 4, 0],
        [2, 3, 9]],

       [[5, 0, 7],
        [8, 6, 1],
        [2, 3, 3]]])

In [35]:
#Matriz identidade
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
#Repetindo uma array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
#copiando arrays da forma errada
a = [1,2,3,4]
b = a # Desse jeito é errado pq se alterar o B o A tbm será alterado
b [1] = 100
print(b)
print(a)

[1, 100, 3, 4]
[1, 100, 3, 4]


In [38]:
#copiando arrays da forma errada
a = [1,2,3,4]
b = a.copy() # Assim é feita uma cópia do array apenas, sem estabelecer vínculos
b [1] = 100
print(b)
print(a)

[1, 100, 3, 4]
[1, 2, 3, 4]


### Funções matemáticas

### Estatísticas

In [68]:
stats = np.array([[1,2,3],[4,5,6]])

In [56]:
#visualizando o valor mínimo
np.min(stats)

2

In [57]:
#visualizando o valor máximo
np.max(stats)

50

In [58]:
#visualizando a média
np.mean(stats)

17.0

In [59]:
#somando os valores
np.sum(stats)

102

In [67]:
#Também é possível calcular essas estatísticas por linha ou coluna

#por coluna
print(np.max(stats, axis = 0))

#por linha
print(np.max(stats, axis = 1))

[10 50 30]
[30 50]


In [69]:
#somando por coluna
np.sum(stats, axis = 0)

array([5, 7, 9])

In [71]:
#somando por linha
np.sum(stats, axis = 1)

array([ 6, 15])

In [72]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

### Reorganizando arrays

In [76]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [77]:
after = before.reshape(4,2)
print(after)
print(after.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [78]:
after = before.reshape(2,2,2)
print(after)
print(after.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [81]:
#Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [89]:
v1.shape

(4,)

In [86]:
#Stackando os vetores
stack = np.vstack([v1,v2])
stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
stack.shape

(2, 4)

In [94]:
#Stackando os vetores
vstack = np.vstack([v1,v2,v1,v2])
vstack

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [99]:
hstacks = np.hstack([h1,h2])

In [100]:
hstacks

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Importando dados

In [110]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Máscaras booleanas e advanced indexing

In [111]:
#Exibindo true nos valores maiores que 50
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [112]:
#indexando usando uma lista
filedata[filedata >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [129]:
#indexando usando uma lista
a = np.array([1,2,3,4,5,6,7,8,9])
posições = [1,2,8]

In [130]:
#São as mesmas operações, indexa usando a posição
print(a[[1,2,8]])
print(a[posições])

[2 3 9]
[2 3 9]


In [136]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [134]:
#Conferindo se algum valor é maior que 50 por coluna
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [135]:
#Conferindo se todos valores são maior que 50 por coluna
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [137]:
#Conferindo se algum valor é maior que 50 por linha
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [138]:
#Conferindo se todos valores são maior que 50 por coluna
np.all(filedata > 50, axis = 1)

array([False, False, False])

In [139]:
#Mais que uma condição: maior que 50 e menor que 100
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [141]:
#Mais que uma condição: não maior que 50 e menor que 100( o til significa não)
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])